library/views/book_view.py
from datetime import date, datetime
from models import libraryBook, rentalBook, bookComment, db
from flask import Blueprint, render_template, redirect, url_for, session, flash, request
from sqlalchemy import and_
from views.main_view import avg_rating
from views.auth_view import login_required

bp = Blueprint("book", __name__, url_prefix="/book")


@bp.route("/<int:book_id>")
def book_detail(book_id):
    book = libraryBook.query.filter(libraryBook.id == book_id).first()
    comments = (
        bookComment.query.filter(bookComment.book_id == book_id)
        .order_by(bookComment.created_at.desc())
        .all()
    )
    return render_template("services/detail.html", book=book, comments=comments)


@bp.route("/<int:book_id>/borrow", methods=["POST"])
def borrow_book(book_id):
    libBook = libraryBook.query.filter(libraryBook.id == book_id).first()
    if not libBook.rented:
        libBook.rented = True
        book = rentalBook(book_id=book_id, user_id=session["email"])
        db.session.add(book)
        db.session.commit()
    else:
        flash("남은 책이 없습니다.")
        book = rentalBook.query.filter(book_id == book_id).first()
    return redirect(url_for("index"))


@bp.route("/lent")
@login_required
def book_lent():
    books = rentalBook.query.filter(
        and_(
            rentalBook.user_id == session["email"],
            rentalBook.return_date <= date.today(),
        )
    ).all()
    return render_template("services/lent.html", books=books, avg_rating=avg_rating)


@bp.route("/return")
@login_required
def book_return():
    books = rentalBook.query.filter(
        and_(
            rentalBook.user_id == session["email"],
            rentalBook.return_date > date.today(),
        )
    ).all()
    return render_template("services/return.html", books=books, avg_rating=avg_rating)


@bp.route("/<int:book_id>/return", methods=["POST"])
@login_required
def return_book(book_id):
    libBook = libraryBook.query.filter(libraryBook.id == book_id).first()
    if libBook.rented:
        libBook.rented = False
        book = (
            rentalBook.query.filter(rentalBook.book_id == book_id)
            .order_by(rentalBook.return_date.desc())
            .first()
        )
        book.return_date = date.today()
        db.session.commit()
    else:
        flash("잘못된 접근 입니다.")

    return redirect(url_for("book.book_return"))


@bp.route("/<int:book_id>/comment", methods=["POST"])
@login_required
def comment(book_id):
    rating = request.form["stars"]
    content = request.form["comment"]
    if rating == "0":
        flash("평가하기를 놓치셨군요. 평가하기를 해주세요.")
    elif not content:
        flash("댓글에 내용이 필요합니다.")
    else:
        c = bookComment(
            book_id=book_id,
            user_id=session["email"],
            rating=rating,
            content=content,
            created_at=datetime.utcnow(),
        )
        db.session.add(c)
        db.session.commit()
    return redirect(url_for("book.book_detail", book_id=book_id))

library/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | 레이서 도서관</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css">
</head>

<body>
    {% block nav %}
    {% include "partials/nav.html" %}
    {% endblock %}
    <section class="content mt-6">
        {% block content %}{% endblock %}
    </section>
    {% if get_flashed_messages() %}
    <div id="alertbox" class="absolute z-0 inset-0 flex justify-center item-center">    
        {% for message in get_flashed_messages() %}
            <div id="alert" class="inline px-6 py-4 my-auto rounded-md bg-red-500 font-bold text-white">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% block script %}{% endblock %}
    <script>
        const box = document.querySelector("#alertbox");
        setTimeout(function() {box.classList.add("hidden");}, 3000);
    </script>
</body>

</html>

library/templates/index.html
{% extends 'base.html' %}
{% block title %}메인{% endblock %}

{% block content %}
{% include "partials/search.html" %}
{% if search %}<div class="mx-10 mb-2">검색결과 : {{ book_count }}권</div>{% endif %}
<div class="grid grid-cols-2 grid-rows-4 mx-10 gap-x-4 gap-y-8 lg:grid-cols-4 lg:grid-rows-2">
    {% for book in books %}
    <form 
        action="{{ url_for('book.borrow_book', book_id=book.id) }}" 
        class="mx-auto p-4 text-center flex flex-col justify-center items-center h-96 w-full bg-white shadow hover:shadow-lg"
        method="POST">
        <img class="m-auto" src="{{book.photo}}" width="110" height="110">
        <a class="h-12 font-semibold" href="{{ url_for('book.book_detail', book_id=book.id) }}"><span>{{book.book_name}}</span></a>
        <div class="flex mt-4">
            {% if avg_rating(book.id) == 0 -%}
            <div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.id) == 1 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.id) == 2 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.id) == 3 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.id) == 4 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- else -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div>
            {%- endif %}
        </div>
        <span class="my-2">
            {% if book.rented %}
            0
            {% else %}
            1
            {% endif %}
            권 남음
        </span>
        {% if g.user and not book.rented %}
        <button 
            class="w-1/2 py-1 mb-2 flex items-center justify-center rounded-md bg-blue-600 text-white"
            type="submit"
        >대여하기</button>
        {% else %}
        <div class="w-1/2 py-1 mb-2 flex items-center justify-center rounded-md bg-blue-300 text-white">대여불가</div>
        {% endif %}
    </form>
    {% endfor %}
</div>
<h5 class="my-8 mx-auto py-4 text-center text-lg">
    {% if page > 1 %}
        <a class="mx-2 px-3 py-2 text-xl" href="?{{searchquery}}page={{page-1}}"><i class="fas fa-chevron-left"></i></a>
    {% endif %}
    {% for p in page_range  %}
        {% if p==page %}
        <a class="mx-2 px-3 py-2 text-white bg-indigo-500 rounded-md" href="?{{searchquery}}page={{p}}">{{p}}</a>
        {% else%}
        <a class="mx-2 px-3 py-2" href="?{{searchquery}}page={{p}}">{{p}}</a>
        {% endif %}
    {% endfor %}
    {% if page <  page_count %}
        <a class="mx-2 px-3 py-2 text-xl" href="?{{searchquery}}page={{page+1}}"><i class="fas fa-chevron-right"></i></a>
    {% endif %}
</h5>
{% endblock %}