library/views/book_view.py
from datetime import date, datetime
from models import libraryBook, rentalBook, bookComment, db
from flask import Blueprint, render_template, redirect, url_for, session, flash, request
from sqlalchemy import and_
from views.main_view import avg_rating
from views.auth_view import login_required

bp = Blueprint("book", __name__, url_prefix="/book")


@bp.route("/<int:book_id>")
def book_detail(book_id):
    book = libraryBook.query.filter(libraryBook.id == book_id).first()
    comments = (
        bookComment.query.filter(bookComment.book_id == book_id)
        .order_by(bookComment.created_at.desc())
        .all()
    )
    return render_template("services/detail.html", book=book, comments=comments)


@bp.route("/<int:book_id>/borrow", methods=["POST"])
def borrow_book(book_id):
    libBook = libraryBook.query.filter(libraryBook.id == book_id).first()
    if not libBook.rented:
        libBook.rented = True
        book = rentalBook(book_id=book_id, user_id=session["email"])
        db.session.add(book)
        db.session.commit()
    else:
        flash("남은 책이 없습니다.")
        book = rentalBook.query.filter(book_id == book_id).first()
    return redirect(url_for("index"))


@bp.route("/lent")
@login_required
def book_lent():
    books = rentalBook.query.filter(
        and_(
            rentalBook.user_id == session["email"],
            rentalBook.return_date <= date.today(),
        )
    ).all()
    return render_template("services/lent.html", books=books, avg_rating=avg_rating)


@bp.route("/return")
@login_required
def book_return():
    books = rentalBook.query.filter(
        and_(
            rentalBook.user_id == session["email"],
            rentalBook.return_date > date.today(),
        )
    ).all()
    return render_template("services/return.html", books=books, avg_rating=avg_rating)


@bp.route("/<int:book_id>/return", methods=["POST"])
@login_required
def return_book(book_id):
    libBook = libraryBook.query.filter(libraryBook.id == book_id).first()
    if libBook.rented:
        libBook.rented = False
        book = (
            rentalBook.query.filter(rentalBook.book_id == book_id)
            .order_by(rentalBook.return_date.desc())
            .first()
        )
        book.return_date = date.today()
        db.session.commit()
    else:
        flash("잘못된 접근 입니다.")

    return redirect(url_for("book.book_return"))


@bp.route("/<int:book_id>/comment", methods=["POST"])
@login_required
def comment(book_id):
    rating = request.form["stars"]
    content = request.form["comment"]
    if rating == "0":
        flash("평가하기를 놓치셨군요. 평가하기를 해주세요.")
    elif not content:
        flash("댓글에 내용이 필요합니다.")
    else:
        c = bookComment(
            book_id=book_id,
            user_id=session["email"],
            rating=rating,
            content=content,
            created_at=datetime.utcnow(),
        )
        db.session.add(c)
        db.session.commit()
    return redirect(url_for("book.book_detail", book_id=book_id))

library/templates/services/detail.html
{% extends 'base.html' %}
{% block title %}{{book.book_name}}{% endblock %}

{% block content %}
<div class="flex flex-col mx-24 my-12 p-24 bg-white">
    <div class="flex justify-between items-center">
        <img src="../static/book_img/{{book.id}}.jpg" width="267" height="267">
        <!-- <div>{{book.photo}}</div>  url이 바뀜... -->
        <div class="flex w-2/3 ml-auto">
            <div class="px-8 border-r-2 border-gray-400">
                <div class="font-semibold py-2">책이름</div>
                <div class="font-semibold py-2">출판사</div>
                <div class="font-semibold py-2">저자</div>
                <div class="font-semibold py-2">출간일</div>
                <div class="font-semibold py-2">페이지 수</div>
                <div class="font-semibold py-2">ISBN 코드</div>
            </div>
            <div class="px-6">
                <div class="pr-10 py-2">{{book.book_name}}</div>
                <div class="pr-10 py-2">{{book.publisher}}</div>
                <div class="pr-10 py-2">{{book.author}}</div>
                <div class="pr-10 py-2">{{book.publication_date}}</div>
                <div class="pr-10 py-2">{{book.pages}}</div>
                <div class="pr-10 py-2">{{book.isbn}}</div>
            </div>
        </div>
    </div>
    <h3 class="mt-12 font-semibold text-2xl border-b border-indigo-300">책 소개</h3>
    <div class="p-6 h-64">
        {{book.description}}
    </div>
    {% include "partials/comment.html" %}
</div>
{% endblock %}

library/templates/services/introduce.html
{% extends 'base.html' %}
{% block title %}{{book_name}}{% endblock %}

{% block content %}
<div>
    <img src="{% static `book_img/{{id}}.jpg` %}" width="267" height="267">
    <div>
        <div>
            <div>책이름</div>
            <div>출판사</div>
            <div>저자</div>
            <div>출간일</div>
            <div>페이지 수</div>
            <div>ISBN 코드</div>
        </div>
        <div>
            <div>{{book_name}}</div>
            <div>{{publisher}}</div>
            <div>{{author}}</div>
            <div>{{publication_date}}</div>
            <div>{{pages}}</div>
            <div>{{isbn}}</div>
        </div>
    </div>
</div>
<h3>책 소개</h3>
<div>
    {{description}}
</div>
{% include "partials/comment.html" %}
{% endblock %}

library/templates/services/lent.html
{% extends 'base.html' %}
{% block title %}대여 기록{% endblock %}

{% block content %}
<div class="grid grid-cols-2 grid-rows-4 mx-10 gap-x-4 gap-y-8 lg:grid-cols-4 lg:grid-rows-2">
    {% for book in books %}
    <div class="mx-auto p-4 text-center flex flex-col justify-center items-center h-96 w-full bg-white shadow hover:shadow-lg">
        <img class="m-auto" src="../static/book_img/{{book.book_id}}.jpg" width="110" height="110">
        <a class="h-12" href="{{ url_for('book.book_detail', book_id=book.book_id) }}"><span>{{book.book.book_name}}</span></a>
        <div class="flex mt-4">
            {% if avg_rating(book.book_id) == 0 -%}
            <div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.book_id) == 1 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.book_id) == 2 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.book_id) == 3 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.book_id) == 4 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- else -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div>
            {%- endif %}
        </div>
        <span>{{book.rental_date}}</span>
        <span>&#8764; {{book.return_date}}</span>
    </div>
    {% endfor %}
    {% if not books %}
    <h1>아직 빌려보신 책이 없습니다.</h1>
    {% endif %}
</div>
{% endblock %}

library/templates/services/return.html
{% extends 'base.html' %}
{% block title %}대여 기록{% endblock %}

{% block content %}
<div class="grid grid-cols-2 grid-rows-4 mx-10 gap-x-4 gap-y-8 lg:grid-cols-4 lg:grid-rows-2">
    {% for book in books %}
    <form 
        action="{{ url_for('book.return_book', book_id=book.book_id) }}"
        class="mx-auto p-4 text-center flex flex-col justify-center items-center h-96 w-full bg-white shadow hover:shadow-lg"
        method="POST">
        <img class="m-auto" src="../static/book_img/{{book.book_id}}.jpg" width="110" height="110">
        <a class="h-12" href="{{ url_for('book.book_detail', book_id=book.book_id) }}"><span>{{book.book.book_name}}</span></a>
        <div class="flex mt-4">
            {% if avg_rating(book.book_id) == 0 -%}
            <div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.book_id) == 1 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.book_id) == 2 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.book_id) == 3 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- elif avg_rating(book.book_id) == 4 -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div>
            {%- else -%}
            <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div>
            {%- endif %}
        </div>
        <span>{{book.rental_date}}</span>
        <button class="w-1/2 flex items-center justify-center rounded-md bg-blue-600 text-white" type="submit">반납하기</button>
    </form>
    {% endfor %}
    {% if not books %}
    <h1>반납하실 책이 없습니다. 읽을만한 책을 찾아보세요!</h1>
    {% endif %}
</div>
{% endblock %}