library/views/auth_view.py
from models import libraryUser, db
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    session,
    flash,
    g,
)
from werkzeug.security import generate_password_hash, check_password_hash
from validator import passwordCheck, emailCheck, usernameCheck
import functools

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=["POST"])
def post_login():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        print(not (email and password))
        user = libraryUser.query.filter(libraryUser.email == email).first()

        if not (email and password):
            errormsg = "빈 칸이 있습니다. 모두 입력해주세요."

        elif not emailCheck(email):
            errormsg = "이메일 형식이 아닙니다."

        elif len(password) < 8:
            errormsg = "비밀번호가 너무 짧습니다. 다시 확인해주세요."

        elif not user:
            errormsg = "아이디 또는 비밀번호가 틀립니다. 다시 한 번 확인해주세요."

        elif not check_password_hash(user.password, password):
            errormsg = "비밀번호가 일치하지 않습니다."

        else:
            session.clear()
            session["username"] = user.username
            session["email"] = user.email
            return redirect(url_for("index"))

        return render_template(
            "auth/login.html",
            errormsg=errormsg,
            email=email,
            password=password,
        )


@bp.route("/login")
def login():
    if g.user:
        flash("잘못된 접근입니다.")
        return redirect(url_for("index"))

    return render_template("auth/login.html")


@bp.route("/register", methods=["POST"])
def post_register():
    username = request.form["username"]
    email = request.form["email"]
    password = request.form["password"]
    password2 = request.form["passwordcheck"]
    user = libraryUser.query.filter(libraryUser.email == email).first()
    if not usernameCheck(username):
        errormsg = "이름을 입력해 주세요."
    elif not emailCheck(email):
        errormsg = "이메일 형식이 아닙니다."
    elif user:
        errormsg = "이미 존재하는 아이디 입니다."
    elif not passwordCheck(password):
        errormsg = "비밀번호가 조건에 일치하지 않습니다."
    elif password != password2:
        errormsg = "비밀번호가 일치하지 않습니다."
    else:
        # 정규표현식으로 체크하기!
        if usernameCheck(username) and emailCheck(email) and passwordCheck(password):
            password = generate_password_hash(password)
            user = libraryUser(email=email, password=password, username=username)
            db.session.add(user)
            db.session.commit()

            session.clear()
            session["username"] = user.username
            session["email"] = user.email
            return redirect(url_for("index"))
        else:
            errormsg = "유효하지 않는 값이 존재합니다."

    return render_template(
        "auth/register.html",
        errormsg=errormsg,
        username=username,
        email=email,
        password=password,
        password2=password2,
    )


@bp.route("/register")
def register():
    if g.user:
        flash("잘못된 접근입니다.")
        return redirect(url_for("index"))

    return render_template("auth/register.html")


@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get("email")
    if user_id:
        g.user = libraryUser.query.filter(libraryUser.email == user_id).first()
    else:
        g.user = None


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("index"))
        return view(**kwargs)

    return wrapped_view

library/views/book_view.py
from datetime import date, datetime
from models import libraryBook, rentalBook, bookComment, db
from flask import Blueprint, render_template, redirect, url_for, session, flash, request
from sqlalchemy import and_
from views.main_view import avg_rating
from views.auth_view import login_required

bp = Blueprint("book", __name__, url_prefix="/book")


@bp.route("/<int:book_id>")
def book_detail(book_id):
    book = libraryBook.query.filter(libraryBook.id == book_id).first()
    comments = (
        bookComment.query.filter(bookComment.book_id == book_id)
        .order_by(bookComment.created_at.desc())
        .all()
    )
    return render_template("services/detail.html", book=book, comments=comments)


@bp.route("/<int:book_id>/borrow", methods=["POST"])
def borrow_book(book_id):
    libBook = libraryBook.query.filter(libraryBook.id == book_id).first()
    if not libBook.rented:
        libBook.rented = True
        book = rentalBook(book_id=book_id, user_id=session["email"])
        db.session.add(book)
        db.session.commit()
    else:
        flash("남은 책이 없습니다.")
        book = rentalBook.query.filter(book_id == book_id).first()
    return redirect(url_for("index"))


@bp.route("/lent")
@login_required
def book_lent():
    books = rentalBook.query.filter(
        and_(
            rentalBook.user_id == session["email"],
            rentalBook.return_date <= date.today(),
        )
    ).all()
    return render_template("services/lent.html", books=books, avg_rating=avg_rating)


@bp.route("/return")
@login_required
def book_return():
    books = rentalBook.query.filter(
        and_(
            rentalBook.user_id == session["email"],
            rentalBook.return_date > date.today(),
        )
    ).all()
    return render_template("services/return.html", books=books, avg_rating=avg_rating)


@bp.route("/<int:book_id>/return", methods=["POST"])
@login_required
def return_book(book_id):
    libBook = libraryBook.query.filter(libraryBook.id == book_id).first()
    if libBook.rented:
        libBook.rented = False
        book = (
            rentalBook.query.filter(rentalBook.book_id == book_id)
            .order_by(rentalBook.return_date.desc())
            .first()
        )
        book.return_date = date.today()
        db.session.commit()
    else:
        flash("잘못된 접근 입니다.")

    return redirect(url_for("book.book_return"))


@bp.route("/<int:book_id>/comment", methods=["POST"])
@login_required
def comment(book_id):
    rating = request.form["stars"]
    content = request.form["comment"]
    if rating == "0":
        flash("평가하기를 놓치셨군요. 평가하기를 해주세요.")
    elif not content:
        flash("댓글에 내용이 필요합니다.")
    else:
        c = bookComment(
            book_id=book_id,
            user_id=session["email"],
            rating=rating,
            content=content,
            created_at=datetime.utcnow(),
        )
        db.session.add(c)
        db.session.commit()
    return redirect(url_for("book.book_detail", book_id=book_id))

library/templates/partials/book_card.html
<div>
    <img src="{{book.photo}}" width="110" height="110">
    <a href="{{ url_for('book.book_detail') }}"><span>{{book.book_name}}</span></a>
    {% block card_content %}
    <span>
        {% if rented == -1 %}
        0
        {% else %}
        1
        {% endif %}
        권 남음
    </span>
    <button type="submit">대여하기</button>
    {% endblock %}
</div>

library/templates/partials/comment.html
<h3 class="mt-12 mb-4 font-semibold text-2xl">댓글</h3>
<div>
    {% for c in comments %}
    <div class="mt-2">
        <div>
            <div class="flex items-end pt-2 border-t border-blue-300">
                <h5 class="font-semibold text-lg">{{c.user.username}}</h5>
                <div class="ml-4 mr-auto text-sm">{{ c.created_at.strftime('%Y-%m-%d') }}</div>
                {% if c.rating == 1 -%}
                <div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
                {%- elif c.rating == 2 -%}
                <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
                {%- elif c.rating == 3 -%}
                <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div><div class="text-blue-300">&#9733;</div>
                {%- elif c.rating == 4 -%}
                <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-300">&#9733;</div>
                {%- else -%}
                <div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div><div class="text-blue-700">&#9733;</div>
                {%- endif %}
            </div>
        </div>
        <div class="mt-2 mb-4">{{c.content}}</div>
    </div>
    {% endfor %}
    {% if not comments %}
        <div class="my-4">아직 댓글이 없습니다. 댓글을 달아주세요.</div>
    {% endif %}
    {% if g.user %}
    <form action="{{ url_for('book.comment', book_id=book.id) }}" method="post">
        <textarea name="comment" id="comment" rows="4" placeholder="댓글달기" class="w-full p-4 mt-4 mx-auto shadow"></textarea>
        <div class="flex justify-end">
            <div class="flex flex-col">
                <div class="flex justify-between items-end">
                    <span class="font-semibold text-gray-700">평가하기</span>
                    <span id="rangeValue" class="text-gray-600 text-sm"></span>
                </div>
                <input type="range" name="stars" id="stars" min="0" max="5" value="0"
                onChange="rangeSlide(this.value)" onmousemove="rangeSlide(this.value)" list="numbers">
                <datalist id="numbers">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                 </datalist>
            </div>
            <input type="submit" value="작성하기" class="py-3 px-8 ml-6 font-semibold rounded-md bg-blue-600 text-white">
        </div>
    </form>
    {% endif %}
</div>
{% block script %}
<script type="text/javascript">
    function rangeSlide(value) {
        document.getElementById('rangeValue').innerHTML = value+"점";
    }
</script>
{% endblock %}

library/templates/partials/nav.html
<nav class="sticky top-0 flex justify-between items-end p-4 bg-white border-b-2 border-indigo-400">
    <h1 class="text-3xl font-bold ">{% block b_title %}<a href="{{ url_for('index') }}">레이서 도서관</a>{% endblock %}</h1>
    <ul class="flex">
        {% if g.user %}
        <li class="mx-4 font-semibold text-xl"><a href="{{ url_for('book.book_lent') }}">대여기록</a></li>
        <li class="mx-4 font-semibold text-xl"><a href="{{ url_for('book.book_return') }}">반납하기</a></li>
        <li class="mx-4 font-semibold text-xl"><a href="{{ url_for('auth.logout') }}">로그아웃</a></li>
        {% else %}
        <li class="mx-4 font-semibold text-xl"><a href="{{ url_for('auth.login') }}">로그인</a></li>
        <li class="mx-4 font-semibold text-xl"><a href="{{ url_for('auth.register') }}">회원가입</a></li>
        {% endif %}
    </ul>
</nav>

library/templates/partials/search.html
<form class="relative mx-10 mb-8 text-gray-400 focus-within:text-gray-900" action="{{ url_for('index') }}" method="get">
    <i class="fa fa-search fa-2x absolute mx-3 my-2" aria-hidden="true"></i>
    <input 
        class="pl-16 pr-24 py-3 w-full shadow-inner border-0 rounded-full focus:outline-none focus:border-transparent" 
        type="text" name="search" id="search" value="{{ search }}" placeholder="검색어를 입력해 주세요." />
    <input class="right-2 px-4 py-3 mt-2 rounded-md bg-indigo-500 hover:bg-indigo-600 text-white hidden" type="submit" value="책 찾기">
</form>